make -C .. src/config/bitcoin-config.h


#echo  CXX  burke_1;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT bitcoin_cli-bitcoin-cli.o -MD -MP -MF .deps/bitcoin_cli-bitcoin-cli.Tpo -c -o bitcoin_cli-bitcoin-cli.o bitcoin-cli.cpp


echo  CXX  rpc/libbitcoin_cli_a-client.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT rpc/libbitcoin_cli_a-client.o -MD -MP -MF rpc/.deps/libbitcoin_cli_a-client.Tpo -c -o rpc/libbitcoin_cli_a-client.o rpc/client.cpp


rm -f libbitcoin_cli.a
echo  AR  libbitcoin_cli.a;/usr/bin/ar cr libbitcoin_cli.a rpc/libbitcoin_cli_a-client.o  
/usr/bin/ranlib libbitcoin_cli.a

echo "  CXX     " support/libbitcoin_util_a-lockedpool.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT support/libbitcoin_util_a-lockedpool.o -MD -MP -MF support/.deps/libbitcoin_util_a-lockedpool.Tpo -c -o support/libbitcoin_util_a-lockedpool.o `test -f 'support/lockedpool.cpp' || echo './'`support/lockedpool.cpp

echo "  CXX     " libbitcoin_util_a-chainparamsbase.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-chainparamsbase.o -MD -MP -MF .deps/libbitcoin_util_a-chainparamsbase.Tpo -c -o libbitcoin_util_a-chainparamsbase.o `test -f 'chainparamsbase.cpp' || echo './'`chainparamsbase.cpp

echo "  CXX     " libbitcoin_util_a-clientversion.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-clientversion.o -MD -MP -MF .deps/libbitcoin_util_a-clientversion.Tpo -c -o libbitcoin_util_a-clientversion.o `test -f 'clientversion.cpp' || echo './'`clientversion.cpp

echo "  CXX     " compat/libbitcoin_util_a-glibc_sanity.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT compat/libbitcoin_util_a-glibc_sanity.o -MD -MP -MF compat/.deps/libbitcoin_util_a-glibc_sanity.Tpo -c -o compat/libbitcoin_util_a-glibc_sanity.o `test -f 'compat/glibc_sanity.cpp' || echo './'`compat/glibc_sanity.cpp

echo "  CXX     " compat/libbitcoin_util_a-glibcxx_sanity.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT compat/libbitcoin_util_a-glibcxx_sanity.o -MD -MP -MF compat/.deps/libbitcoin_util_a-glibcxx_sanity.Tpo -c -o compat/libbitcoin_util_a-glibcxx_sanity.o `test -f 'compat/glibcxx_sanity.cpp' || echo './'`compat/glibcxx_sanity.cpp

echo "  CXX     " compat/libbitcoin_util_a-strnlen.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT compat/libbitcoin_util_a-strnlen.o -MD -MP -MF compat/.deps/libbitcoin_util_a-strnlen.Tpo -c -o compat/libbitcoin_util_a-strnlen.o `test -f 'compat/strnlen.cpp' || echo './'`compat/strnlen.cpp

echo "  CXX     " libbitcoin_util_a-fs.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-fs.o -MD -MP -MF .deps/libbitcoin_util_a-fs.Tpo -c -o libbitcoin_util_a-fs.o `test -f 'fs.cpp' || echo './'`fs.cpp

echo "  CXX     " libbitcoin_util_a-random.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-random.o -MD -MP -MF .deps/libbitcoin_util_a-random.Tpo -c -o libbitcoin_util_a-random.o `test -f 'random.cpp' || echo './'`random.cpp

echo "  CXX     " rpc/libbitcoin_util_a-protocol.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT rpc/libbitcoin_util_a-protocol.o -MD -MP -MF rpc/.deps/libbitcoin_util_a-protocol.Tpo -c -o rpc/libbitcoin_util_a-protocol.o `test -f 'rpc/protocol.cpp' || echo './'`rpc/protocol.cpp

echo "  CXX     " support/libbitcoin_util_a-cleanse.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT support/libbitcoin_util_a-cleanse.o -MD -MP -MF support/.deps/libbitcoin_util_a-cleanse.Tpo -c -o support/libbitcoin_util_a-cleanse.o `test -f 'support/cleanse.cpp' || echo './'`support/cleanse.cpp

echo "  CXX     " libbitcoin_util_a-sync.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-sync.o -MD -MP -MF .deps/libbitcoin_util_a-sync.Tpo -c -o libbitcoin_util_a-sync.o `test -f 'sync.cpp' || echo './'`sync.cpp

echo "  CXX     " libbitcoin_util_a-threadinterrupt.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-threadinterrupt.o -MD -MP -MF .deps/libbitcoin_util_a-threadinterrupt.Tpo -c -o libbitcoin_util_a-threadinterrupt.o `test -f 'threadinterrupt.cpp' || echo './'`threadinterrupt.cpp

echo "  CXX     " libbitcoin_util_a-util.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-util.o -MD -MP -MF .deps/libbitcoin_util_a-util.Tpo -c -o libbitcoin_util_a-util.o `test -f 'util.cpp' || echo './'`util.cpp

echo "  CXX     " libbitcoin_util_a-utilmoneystr.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-utilmoneystr.o -MD -MP -MF .deps/libbitcoin_util_a-utilmoneystr.Tpo -c -o libbitcoin_util_a-utilmoneystr.o `test -f 'utilmoneystr.cpp' || echo './'`utilmoneystr.cpp

echo "  CXX     " libbitcoin_util_a-utilstrencodings.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-utilstrencodings.o -MD -MP -MF .deps/libbitcoin_util_a-utilstrencodings.Tpo -c -o libbitcoin_util_a-utilstrencodings.o `test -f 'utilstrencodings.cpp' || echo './'`utilstrencodings.cpp

echo "  CXX     " libbitcoin_util_a-utiltime.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-utiltime.o -MD -MP -MF .deps/libbitcoin_util_a-utiltime.Tpo -c -o libbitcoin_util_a-utiltime.o `test -f 'utiltime.cpp' || echo './'`utiltime.cpp

rm -f libbitcoin_util.a
echo "  AR      " libbitcoin_util.a;/usr/bin/ar cr libbitcoin_util.a support/libbitcoin_util_a-lockedpool.o libbitcoin_util_a-chainparamsbase.o libbitcoin_util_a-clientversion.o compat/libbitcoin_util_a-glibc_sanity.o compat/libbitcoin_util_a-glibcxx_sanity.o compat/libbitcoin_util_a-strnlen.o libbitcoin_util_a-fs.o libbitcoin_util_a-random.o rpc/libbitcoin_util_a-protocol.o support/libbitcoin_util_a-cleanse.o libbitcoin_util_a-sync.o libbitcoin_util_a-threadinterrupt.o libbitcoin_util_a-util.o libbitcoin_util_a-utilmoneystr.o libbitcoin_util_a-utilstrencodings.o libbitcoin_util_a-utiltime.o    
/usr/bin/ranlib libbitcoin_util.a

#univalue/libunivalue.la: univalue/lib/univalue.cpp univalue/lib/univalue_write.cpp univalue/lib/univalue_utffilter.h univalue/lib/univalue_escapes.h univalue/lib/univalue_read.cpp univalue/include/univalue.h
make  -C . univalue/libunivalue.la 

echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-aes.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-aes.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-aes.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-aes.o `test -f 'crypto/aes.cpp' || echo './'`crypto/aes.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-aes.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-aes.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-chacha20.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-chacha20.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-chacha20.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-chacha20.o `test -f 'crypto/chacha20.cpp' || echo './'`crypto/chacha20.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-chacha20.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-chacha20.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-hmac_sha256.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-hmac_sha256.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-hmac_sha256.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-hmac_sha256.o `test -f 'crypto/hmac_sha256.cpp' || echo './'`crypto/hmac_sha256.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-hmac_sha256.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-hmac_sha256.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-hmac_sha512.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-hmac_sha512.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-hmac_sha512.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-hmac_sha512.o `test -f 'crypto/hmac_sha512.cpp' || echo './'`crypto/hmac_sha512.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-hmac_sha512.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-hmac_sha512.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-ripemd160.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-ripemd160.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-ripemd160.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-ripemd160.o `test -f 'crypto/ripemd160.cpp' || echo './'`crypto/ripemd160.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-ripemd160.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-ripemd160.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-sha1.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-sha1.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-sha1.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-sha1.o `test -f 'crypto/sha1.cpp' || echo './'`crypto/sha1.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-sha1.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-sha1.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-sha256.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-sha256.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-sha256.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-sha256.o `test -f 'crypto/sha256.cpp' || echo './'`crypto/sha256.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-sha256.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-sha256.Po
echo "  CXX     " crypto/crypto_libbitcoin_crypto_a-sha512.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I./config -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT crypto/crypto_libbitcoin_crypto_a-sha512.o -MD -MP -MF crypto/.deps/crypto_libbitcoin_crypto_a-sha512.Tpo -c -o crypto/crypto_libbitcoin_crypto_a-sha512.o `test -f 'crypto/sha512.cpp' || echo './'`crypto/sha512.cpp
mv -f crypto/.deps/crypto_libbitcoin_crypto_a-sha512.Tpo crypto/.deps/crypto_libbitcoin_crypto_a-sha512.Po
rm -f crypto/libbitcoin_crypto.a
echo "  AR      " crypto/libbitcoin_crypto.a;/usr/bin/ar cr crypto/libbitcoin_crypto.a crypto/crypto_libbitcoin_crypto_a-aes.o crypto/crypto_libbitcoin_crypto_a-chacha20.o crypto/crypto_libbitcoin_crypto_a-hmac_sha256.o crypto/crypto_libbitcoin_crypto_a-hmac_sha512.o crypto/crypto_libbitcoin_crypto_a-ripemd160.o crypto/crypto_libbitcoin_crypto_a-sha1.o crypto/crypto_libbitcoin_crypto_a-sha256.o crypto/crypto_libbitcoin_crypto_a-sha512.o  
/usr/bin/ranlib crypto/libbitcoin_crypto.a

echo "  CXX     " libbitcoin_cli-bitcoin-cliapi.o;g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj  -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_util_a-utiltime.o -MD -MP -MF .deps/libbitcoin_util_a-utiltime.Tpo -c -o libbitcoin_cli-bitcoin-cliapi.o `test -f 'bitcoin-cliapi.cpp' || echo './'`bitcoin-cliapi.cpp

echo " CXX libbitcoin_cliapi_a-pubkey.o "; g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -I/usr/include/libdb4/ -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_cliapi_a-pubkey.o -MD -MP -MF .deps/libbitcoin_cliapi_a-pubkey.Tpo -c -o libbitcoin_cliapi_a-pubkey.o pubkey.cpp	

echo " CXX libbitcoin_cliapi_a-key.o"; g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -I/usr/include/libdb4/ -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_cliapi_a-key.o -MD -MP -MF .deps/libbitcoin_common_a-key.Tpo -c -o libbitcoin_cliapi_a-key.o key.cpp

echo  "CXX  libbitcoin_cliapi_a-hash.o"; g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -I/usr/include/libdb4/ -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_consensus_a-hash.o -MD -MP -MF .deps/libbitcoin_consensus_a-hash.Tpo -c -o libbitcoin_cliapi_a-hash.o hash.cpp

echo  "CXX  libbitcoin_cliapi_a-uint256.o";g++ -std=c++11 -DHAVE_CONFIG_H -I. -I../src/config  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I. -I./obj -I/usr/include/libdb4/ -DBOOST_SP_USE_STD_ATOMIC -DBOOST_AC_USE_STD_ATOMIC -pthread -I/usr/include -DBOOST_NO_SCOPED_ENUMS -DBOOST_NO_CXX11_SCOPED_ENUMS -I./leveldb/include -I./leveldb/helpers/memenv   -I./secp256k1/include -I./univalue/include -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS -Wstack-protector -fstack-protector-all  -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -MT libbitcoin_cliapi_a-uint256.o -MD -MP -MF .deps/libbitcoin_consensus_a-uint256.Tpo -c -o libbitcoin_cliapi_a-uint256.o uint256.cpp

rm libbitcoin_cliapi.a
echo "  AR      " libbitcoin_cliapi.a;/usr/bin/ar cr libbitcoin_cliapi.a libbitcoin_cli-bitcoin-cliapi.o rpc/libbitcoin_cli_a-client.o    crypto/crypto_libbitcoin_crypto_a-aes.o crypto/crypto_libbitcoin_crypto_a-chacha20.o crypto/crypto_libbitcoin_crypto_a-hmac_sha256.o crypto/crypto_libbitcoin_crypto_a-hmac_sha512.o crypto/crypto_libbitcoin_crypto_a-ripemd160.o crypto/crypto_libbitcoin_crypto_a-sha1.o crypto/crypto_libbitcoin_crypto_a-sha256.o crypto/crypto_libbitcoin_crypto_a-sha512.o support/libbitcoin_util_a-lockedpool.o libbitcoin_util_a-chainparamsbase.o libbitcoin_util_a-clientversion.o compat/libbitcoin_util_a-glibc_sanity.o compat/libbitcoin_util_a-glibcxx_sanity.o compat/libbitcoin_util_a-strnlen.o libbitcoin_util_a-fs.o libbitcoin_util_a-random.o rpc/libbitcoin_util_a-protocol.o support/libbitcoin_util_a-cleanse.o libbitcoin_util_a-sync.o libbitcoin_util_a-threadinterrupt.o libbitcoin_util_a-util.o libbitcoin_util_a-utilmoneystr.o libbitcoin_util_a-utilstrencodings.o libbitcoin_util_a-utiltime.o  crypto/crypto_libbitcoin_crypto_a-aes.o crypto/crypto_libbitcoin_crypto_a-chacha20.o crypto/crypto_libbitcoin_crypto_a-hmac_sha256.o crypto/crypto_libbitcoin_crypto_a-hmac_sha512.o crypto/crypto_libbitcoin_crypto_a-ripemd160.o crypto/crypto_libbitcoin_crypto_a-sha1.o crypto/crypto_libbitcoin_crypto_a-sha256.o crypto/crypto_libbitcoin_crypto_a-sha512.o support/libbitcoin_util_a-lockedpool.o libbitcoin_util_a-chainparamsbase.o libbitcoin_util_a-clientversion.o compat/libbitcoin_util_a-glibc_sanity.o compat/libbitcoin_util_a-glibcxx_sanity.o compat/libbitcoin_util_a-strnlen.o libbitcoin_util_a-fs.o libbitcoin_util_a-random.o rpc/libbitcoin_util_a-protocol.o support/libbitcoin_util_a-cleanse.o libbitcoin_util_a-sync.o libbitcoin_util_a-threadinterrupt.o libbitcoin_util_a-util.o libbitcoin_util_a-utilmoneystr.o libbitcoin_util_a-utilstrencodings.o libbitcoin_util_a-utiltime.o  libbitcoin_cliapi_a-pubkey.o   libbitcoin_cliapi_a-key.o  libbitcoin_cliapi_a-hash.o libbitcoin_cliapi_a-uint256.o 

#g++ -std=c++11 -Wstack-protector -fstack-protector-all -fPIE -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -pie -o bitcoin-cli bitcoin_cli-bitcoin-cli.o libbitcoin_cli.a univalue/.libs/libunivalue.a libbitcoin_util.a crypto/libbitcoin_crypto.a -L/usr/lib64 -lboost_system -lboost_filesystem -lboost_program_options-mt -lboost_thread -lboost_chrono-mt -lssl -lcrypto -levent -pthread
